name: devbuild

on:
  push:
  pull_request:
  schedule:
    - cron: '34 17 * * *'

jobs:
  build_ubuntu:

    if: ${{ github.event_name != '' || (github.event_name == '' && github.repository_owner == 'solvcon') }}

    name: build_${{ matrix.os }}_${{ matrix.cmake_build_type }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # ubuntu-20.04 does not have built-in qt6
        os: [ubuntu-22.04]
        cmake_build_type: [Release]

      fail-fast: false

    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: event name
        run: |
          echo "github.event_name: ${{ github.event_name }}"
      - name: dependency by apt
        run: |
          sudo apt-get -qqy update
          sudo apt-get -qy install \
              sudo curl git build-essential make cmake libc6-dev gcc g++ \
              python3 python3-pip python3-venv

      - name: dependency by pip
        run: |
          sudo pip3 install sphinx furo

      - name: show dependency
        # Copy the commands from contrib/dependency/showdep.sh
        run: |
          echo "gcc path: $(which gcc)"
          echo "gcc version: $(gcc --version)"
          echo "cmake path: $(which cmake)"
          echo "cmake version: $(cmake --version)"
          echo "python3 path: $(which python3)"
          echo "python3 version: $(python3 --version)"
          echo "pip3 path: $(which pip3)"
          python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'

      - name: make html
        run: |
          make html